const XLFN_FUNCTION_NAMES = [
    'BETA.DIST',
    'BETA.INV',
    'BINOM.DIST',
    'BINOM.INV',
    'CEILING.PRECISE',
    'CHISQ.DIST',
    'CHISQ.DIST.RT',
    'CHISQ.INV',
    'CHISQ.INV.RT',
    'CHISQ.TEST',
    'CONFIDENCE.NORM',
    'CONFIDENCE.T',
    'COVARIANCE.P',
    'COVARIANCE.S',
    'ERF.PRECISE',
    'ERFC.PRECISE',
    'EXPON.DIST',
    'F.DIST',
    'F.DIST.RT',
    'F.INV',
    'F.INV.RT',
    'F.TEST',
    'FLOOR.PRECISE',
    'GAMMA.DIST',
    'GAMMA.INV',
    'GAMMALN.PRECISE',
    'LOGNORM.DIST',
    'LOGNORM.INV',
    'MODE.MULT',
    'MODE.SNGL',
    'NEGBINOM.DIST',
    'NETWORKDAYS.INTL',
    'NORM.DIST',
    'NORM.INV',
    'NORM.S.DIST',
    'NORM.S.INV',
    'PERCENTILE.EXC',
    'PERCENTILE.INC',
    'PERCENTRANK.EXC',
    'PERCENTRANK.INC',
    'POISSON.DIST',
    'QUARTILE.EXC',
    'QUARTILE.INC',
    'RANK.AVG',
    'RANK.EQ',
    'STDEV.P',
    'STDEV.S',
    'T.DIST',
    'T.DIST.2T',
    'T.DIST.RT',
    'T.INV',
    'T.INV.2T',
    'T.TEST',
    'VAR.P',
    'VAR.S',
    'WEIBULL.DIST',
    'Z.TEST',
    'BASE',
    'ACOT',
    'ACOTH',
    'ARABIC',
    'AVERAGEIFS',
    'BINOM.DIST.RANGE',
    'BITAND',
    'BITLSHIFT',
    'BITOR',
    'BITRSHIFT',
    'BITXOR',
    'CEILING.MATH',
    'COMBINA',
    'COT',
    'COTH',
    'CSC',
    'CSCH',
    'DAYS',
    'DBCS',
    'DECIMAL',
    'ENCODEURL',
    'FILTERXML',
    'FLOOR.MATH',
    'FORMULATEXT',
    'GAMMA',
    'GAUSS',
    'IFNA',
    'IMCOSH',
    'IMCOT',
    'IMCSC',
    'IMCSCH',
    'IMSEC',
    'IMSECH',
    'IMSINH',
    'IMTAN',
    'ISFORMULA',
    'ISO.CEILING',
    'ISOWEEKNUM',
    'MUNIT',
    'NUMBERVALUE',
    'PDURATION',
    'PERMUTATIONA',
    'PHI',
    'RRI',
    'SEC',
    'SECH',
    'SHEET',
    'SHEETS',
    'SKEW.P',
    'UNICHAR',
    'UNICODE',
    'WEBSERVICE',
    'XOR',
    'FORECAST.ET2',
    'FORECAST.ETS.CONFINT',
    'FORECAST.ETS.SEASONALITY',
    'FORECAST.ETS.STAT',
    'FORECAST.LINEAR',
    'SWITCH',
    'CONCAT',
    'IFS',
    'MAXIFS',
    'MINIFS',
    'TEXTJOIN',
    'ANCHORARRAY',
    'ARRAYTOTEXT',
    'BYCOL',
    'BYROW',
    'CALL',
    'CHOOSECOLS',
    'CHOOSEROWS',
    'DROP',
    'EXPAND',
    'FILTER',
    'GROUPBY',
    'HSTACK',
    'ISOMITTED',
    'LAMBDA',
    'LET',
    'MAKEARRAY',
    'MAP',
    'RANDARRAY',
    'REDUCE',
    'REGISTER.ID',
    'SCAN',
    'SEQUENCE',
    'SINGLE',
    'SORT',
    'SORTBY',
    'TAKE',
    'TEXTAFTER',
    'TEXTBEFORE',
    'TEXTSPLIT',
    'TOCOL',
    'TOROW',
    'UNIQUE',
    'VALUETOTEXT',
    'VSTACK',
    'WRAPCOLS',
    'WRAPROWS',
    'XLOOKUP',
    'XMATCH',
] as const;

const XLWS_FUNCTION_NAMES = ['FILTER', 'SORT'] as const;

function escapeRegex(value: string): string {
    return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

export class FunctionPrefix {
    private static readonly XLFN_REGEX = new RegExp(
        `(?:_xlfn\\.)?((?:_xlws\\.)?(?:${XLFN_FUNCTION_NAMES.map(escapeRegex).join('|')}))\\s*\\(`,
        'giu',
    );

    private static readonly XLWS_REGEX = new RegExp(
        `(?<!_xlws\\.)(${XLWS_FUNCTION_NAMES.map(escapeRegex).join('|')})\\s*\\(`,
        'giu',
    );

    private static readonly SPILL_REGEX = /(([A-Z]+[0-9]+)(:[A-Z]+[0-9]+)?)(#)/giu;

    public static addFunctionPrefix(functionString: string): string {
        const withAnchorArrays = functionString.replace(FunctionPrefix.SPILL_REGEX, 'ANCHORARRAY($1)');
        const withXlfn = withAnchorArrays.replace(FunctionPrefix.XLFN_REGEX, '_xlfn.$1(');

        return withXlfn.replace(FunctionPrefix.XLWS_REGEX, '_xlws.$1(');
    }
}
